%YAML:1.0
---

####################################
# 该文件用于初始化一些参数
# 同时，在base.h中开启USER_TUNE_PARAM该文件参数每隔1s可被重复加载，从而实现热调参的功能

##########################################
# 匀角速度卡尔曼滤波器调参
R_00: 1326 #13131.0 # 角度测量值方�??
R_11: 15290 #12690 #2690 #6500
R_22: 1700 #100 #13131.0 # 角度测量值方�??

Q_00: 120  #20.0 # 过程角度�??声方�??
Q_11: 1200 # 过程角速度�??声方�??3282.80
Q_22: 2620   #300

Q_33: 1700 #1500 #17 
Q_44: 3000 #1000 
Q_55: 100

Q_66: 1000 #3000 #500 #20
Q_77: 1313

dis_confidence: 1
v_confidence: 0.2
a_confidence: 0
##########################################


#########################################
# 时间帧对齐参数
synchronizor: -5
#########################################

#########################################
# 发弹延时,单位s
shoot_delay: 0.08
#########################################


#########################################
# 平移量
X_OFFSET: -85.5
Y_OFFSET: -45.0  #-107.518
Z_OFFSET: 99 #73.771
#########################################

#########################################
# 弹丸质量
bullet_m: 3.2e-3 # 小弹丸
#bullet_m: 4.1e-2 # 大弹丸

# 弹丸空气阻力系数
bullet_k: 7.1655e-5 # 小弹丸
#bullet_k: 4.5857e-4 # 大弹丸

bullet_r: 8.4e-3 # 小弹丸半径
# bullet_r: 21.25e-3 # 大弹丸半径
#########################################


#########################################
# 接收角度偏移量调节
armor_yaw_offset: -0.2
armor_pitch_offset: -2.1
armor_roll_offset: 0.1

pitchBase0: -8.43 
pitchError0: -1.5360350801588756
kPitch0: 0.1893426081423921
pitchBase1: -7.8 
pitchError1: -1.45794932527118
kPitch1: 0.123945642678882
pitchBase2: -7.38 
pitchError2: -1.3924546064067775
kPitch2: 0.15593980682000572
pitchBase3: -6.73 
pitchError3: -1.2453231513029595
kPitch3: 0.22635608477510494

rune_yaw_offset: 0.0
rune_pitch_offset: 0.03
rune_k: -0.01
rune_low_pitch: -1.14
# 发送角度偏移量
send_armor_pitch_default: 1.4
send_armor_yaw_default: 0.0

send_rune_pitch_offset: 0.30
send_rune_yaw_offset: 0.00
rune_trajectory_k: 0.055
#########################################


#########################################
#########################################
# 击打前哨战参数
outpost_height: 1.23 #单位m
robot_height: 0.355 #单位m



# 旋转前哨站接收偏移数据
dynatic_yaw_offset: 0.0
dynatic_pitch_offset: 1.36 #-2.8 #-2.6 #-2.8 #0.0 #-2.4
dynatic_roll_offset: -0.1 #0.8

# 旋转前哨站发送pitch偏移量
send_dynatic_pitch_offset: -0.1
# 旋转前哨站发送yaw偏移量
send_dynatic_yaw_offset: -0.0
# 旋转前哨站发送延时
dynatic_shoot_delay: 0

# 旋转前哨站击打比例(0.5是全占比，禁止大于0.5)
dynatic_shoot_proportion: 0.35


#########################################


#########################################


# ekf参数
#########################################
Cov_mu: !!opencv-matrix
   rows: 5
   cols: 1
   dt: d
   data: [20, 20, 10, 20, 0.01]
   # data: [0.1, 0.1, 0.1, 50, 1]
# 过程噪声协方差矩阵，含义为：D(a_x), D(a_y), D(a_z), D(a_theta), D(v_r)

R: !!opencv-matrix
   rows: 4
   cols: 1
   dt: d
   data: [0.1, 0.1, 0.5, 0.5]
#########################################