%YAML:1.0
---
### Robot ID:dva
####################################
# 该文件用于初始化一些参数
# 同时，在base.h中开启USER_TUNE_PARAM该文件参数每隔1s可被重复加载，从而实现热调参的功能

##########################################
# 匀角速度卡尔曼滤波器调参
R_00: 1313.0 # 角度测量值方�??
R_11: 20
R_22: 1.0 # 角度测量值方�??

Q_00: 33000 # 过程角度�??声方�??
Q_11: 3282 # 过程角速度�??声方�??
Q_22: 1000
Q_33: 1000
Q_44: 1200
Q_55: 33
Q_66: 328280.0

dis_confidence: 1
v_confidence: 1
a_confidence: 0
##########################################
# EKF参数
R_0: 6 #0.000006
R_1: 1458 #0.001458  
R_2: 1 #0.000001

w_y: 42.9718    #0.75*180/Util::PI;
w_yy: 183.3465   #3.2*180/Util::PI;
w_d:  57.2958   #180/Util::PI;
w_dd: 57.2958  #180/Util::PI;
w_p: 2.8648   #0.05*180/Util::PI;
w_pp: 5729.5780 #100*180/Util::PI;

#########################################
# 时间帧对齐参数
synchronizor: 0
#########################################

#########################################
# 发弹延时,单位s
shoot_delay: 0
#########################################


#########################################
# 平移量
X_OFFSET: 0.0
Y_OFFSET: -50.0
Z_OFFSET: 140.0
#########################################

#########################################
# 弹丸质量
bullet_m: 3.2e-3 # 小弹丸
# bullet_m: 4.1e-2 # 大弹丸

# 弹丸空气阻力系数
bullet_k: 7.1655e-5 # 小弹丸
# bullet_k: 4.5857e-4 # 大弹丸

bullet_r: 8.4e-3 # 小弹丸半径
# bullet_r: 21.25e-3 # 大弹丸半径
#########################################


#########################################
# 接收角度偏移量调节
armor_yaw_offset: -0.8
armor_pitch_offset: 0
armor_roll_offset: 1.2 #0.8
rune_yaw_offset: 0.0
rune_pitch_offset: 0.0
# 发送角度偏移量
send_armor_pitch_default: -1.5
send_armor_yaw_default: 0.9
#########################################

# 旋转前哨站接收偏移数据
dynatic_yaw_offset: 0.1 #0.5
dynatic_pitch_offset: -2.8 #-2.8 #-2.6 #-2.8 #0.0 #-2.4
dynatic_roll_offset: 0.6 #0.8

# 旋转前哨站发送pitch偏移量
send_dynatic_pitch_offset: 0.0 #0.4 #-0.2
# 旋转前哨站发送yaw偏移量
send_dynatic_yaw_offset: -0.0 # -0.3
# 旋转前哨站发送延时
dynatic_shoot_delay: 100 #125 #120

# 旋转前哨站击打比例(0.5是全占比，禁止大于0.5)
dynatic_shoot_proportion: 0.4
#########################################
# 击打前哨战参数
outpost_height: 1.23 #单位m
robot_height: 0.4 #单位m


#########################################

# ekf参数
#########################################
Cov_mu: !!opencv-matrix
   rows: 5
   cols: 1
   dt: d
   data: [10, 10, 10, 20, 0.01]
   # data [0.1, 0.1, 0.1, 50, 1]
# 过程噪声协方差矩阵，含义为：D(a_x), D(a_y), D(a_z), D(a_theta), D(v_r)

R: !!opencv-matrix
   rows: 4
   cols: 1
   dt: d
   data: [0.1, 0.1, 0.5, 0.5]
#########################################
