%YAML:1.0
---
### Robot ID: 无人机
####################################
# 该文件用于初始化一些参�???
# 同时，在base.h�???开启USER_TUNE_PARAM该文件参数每�???1s�???�???重�?�加载，从而实现热调参的功�???

##########################################
# 匀角速度卡尔曼滤波器调参
R_00: 3600 #1313.0 # 角度测量值方�???
R_11: 3050 #20
R_22: 5500 #1.0 # 角度测量值方�???
Q_00: 33.0 # 过程角度�???声方�???
Q_11: 10000 #52828.0 # 过程角速度�???声方�???
Q_22: 262
Q_33: 33
Q_44: 1
Q_55: 33
Q_66: 50000 #328280.0
dis_confidence: 1
v_confidence: 1
a_confidence: 0
##########################################
# EKF参数
w_y: 42.9718    #0.75*180/Util::PI;
w_yy: 183.3465   #3.2*180/Util::PI;
w_d: 57.2958   #180/Util::PI;
w_dd: 57.2958  #180/Util::PI;
w_p: 2.8648   #0.05*180/Util::PI;
w_pp: 5729.5780 #100*180/Util::PI;

#########################################
# 鏃堕棿甯э�??锟介綈鍙傛暟
synchronizor: 0
#########################################

#########################################
# 鍙戝脊�?�舵�?,鍗曚綅s
shoot_delay: 0.0
#########################################


#########################################
# 平移�???
X_OFFSET: 0.0
Y_OFFSET: 65.0
Z_OFFSET: 110.0
#########################################

#########################################
# 弹丸质量
bullet_m: 3.2e-3 # 小弹丸
#bullet_m: 4.1e-2 # 大弹丸

# 弹丸空气阻力系数
bullet_k: 7.1655e-5 # 小弹丸
#bullet_k: 4.5857e-4 # 大弹丸

bullet_r: 8.4e-3 # 小弹丸半径
# bullet_r: 21.25e-3 # 大弹丸半径
#########################################


#########################################
# 接收角度偏移量调�???
armor_yaw_offset: 0.0
armor_pitch_offset: 1.2
armor_roll_offset: -0.4 #-0.1

rune_yaw_offset: 0.0
rune_pitch_offset: 0.0
# 发送�?�度偏移�???
send_armor_pitch_default: -1.3
send_armor_yaw_default: -0.8
#########################################


#########################################
# 击打前哨战参�???
outpost_height: 1.23 #单位m
robot_height: 0.4 #单位m
MIN_OUTPOST_RATIO: 0.8
MAX_OUTPOST_RATIO: 1.2
OUTPOST_OFFSET_TIME: 600

#########################################

# ekf参数
#########################################
Cov_mu: !!opencv-matrix
   rows: 5
   cols: 1
   dt: d
   data: [5, 5, 0.5, 50, 1]
   # data: [0.1, 0.1, 0.1, 50, 1]
# 过程噪声协方差矩阵，含义为：D(a_x), D(a_y), D(a_z), D(a_theta), D(v_r)

R: !!opencv-matrix
   rows: 4
   cols: 1
   dt: d
   data: [0.01, 0.01, 0.2, 0.09]
#########################################
