%YAML:1.0
---
### Robot ID: 英雄
####################################
# 该文件用于初始化一些参数
# 同时，在base.h中开启USER_TUNE_PARAM该文件参数每隔1s可被重复加载，从而实现热调参的功能

##########################################
# 匀角速度卡尔曼滤波器调参
R_00: 10897  #1313.0 # 角度测量值方�??
R_11: 15500  #2500
R_22: 1704  #1.0 # 角度测量值方�??

Q_00: 33.0 # 过程角度�??声方�??
Q_11: 22830 #228280.0 # 过程角速度�??声方�??
Q_22: 12200 #162000

Q_33: 10  #33
Q_44: 2000
Q_55: 1000 #10

Q_66: 20
Q_77: 228280.0

dis_tolerance: 0.3
dis_confidence: 1
v_confidence: 1
a_confidence: 0
##########################################
# EKF参数
w_y: 42.9718    #0.75*180/Util::PI;
w_yy: 183.3465   #3.2*180/Util::PI;
w_d: 57.2958   #180/Util::PI;
w_dd: 57.2958  #180/Util::PI;
w_p: 2.8648   #0.05*180/Util::PI;
w_pp: 5729.5780 #100*180/Util::PI;

#########################################
# 时间帧对齐参数
synchronizor: 0
#########################################

#########################################
# 发弹延时,单位s
shoot_delay: 0.125 #0.17
#########################################





#########################################
# 平移量
X_OFFSET: -72.00
Y_OFFSET: -77.66 #-110 #80 #-77.66
Z_OFFSET: 99.15
#########################################

#########################################
# 弹丸质量
# bullet_m: 3.2e-3 # 小弹丸
bullet_m: 4.1e-2 # 大弹丸

# 弹丸空气阻力系数
# bullet_k: 7.1655e-5 # 小弹丸
bullet_k: 4.5857e-4 # 大弹丸

# bullet_r: 8.4e-3 # 小弹丸半径
bullet_r: 21.25e-3 # 大弹丸半径
#########################################


#########################################
# 接收角度偏移量调节
armor_yaw_offset: -1 #0.8
armor_pitch_offset: -2.3 #-2.8 #-2.6 #-2.8 #0.0 #-2.4
armor_roll_offset: 0.6 #0.8




pitchError0: -3.22962549
kPitch0: 0.24506097191011222
pitchBase1: -7.41 
pitchError1: -3.04776334
kPitch1: 0.19143384210526349
pitchBase2: -7.2 
pitchError2: -3.04361238
kPitch2: 0.01976647619047637
pitchBase3: -2.5497226 
pitchError3: -2.5497225972966984
kPitch3: 0.1062065206482739

rune_yaw_offset: 0.0
rune_pitch_offset: 0.0
# 发送角度偏移量
send_armor_pitch_default: 0.1 #-0.2 #-1.4 #-1.5 #-1.65
send_armor_yaw_default: -0.0 #-0.3

# 旋转前哨站接收偏移数据
dynatic_yaw_offset: 0.1 #0.5
dynatic_pitch_offset: -2.8 #-2.8 #-2.6 #-2.8 #0.0 #-2.4
dynatic_roll_offset: 0.6 #0.8

# 旋转前哨站发送pitch偏移量
send_dynatic_pitch_offset: 0.0 #0.4 #-0.2
# 旋转前哨站发送yaw偏移量
send_dynatic_yaw_offset: -0.0 # -0.3
# 旋转前哨站发送延时
dynatic_shoot_delay: 100 #125 #120

# 旋转前哨站击打比例(0.5是全占比，禁止大于0.5)
dynatic_shoot_proportion: 0.5

# 弹速
burst_speed: 15.8


#########################################


#########################################
# 击打前哨战参数
outpost_height: 1.23 #单位m
robot_height: 0.4 #单位m
MIN_OUTPOST_RATIO: 0.7
MAX_OUTPOST_RATIO: 1.2
OUTPOST_OFFSET_TIME: 630

#########################################

# ekf参数
#########################################
Cov_mu: !!opencv-matrix
   rows: 5
   cols: 1
   dt: d
   data: [5, 5, 0.5, 50, 1]
   # data: [0.1, 0.1, 0.1, 50, 1]
# 过程噪声协方差矩阵，含义为：D(a_x), D(a_y), D(a_z), D(a_theta), D(v_r)

R: !!opencv-matrix
   rows: 4
   cols: 1
   dt: d
   data: [0.01, 0.01, 0.2, 0.09]
#########################################
